project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipes.urls'))
]

recipes/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from . import views

app_name = 'recipes'

urlpatterns = [
    path('', views.my_home, name="home"),
    path('recipes/category/<int:category_id>/',
         views.category, name="category"),
    path('recipes/<int:id>/', views.recipe, name="recipe"),
]

# definir local de imagens
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

recipes/models.py
from django.contrib.auth.models import User
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=65)

    def __str__(self):
        return self.name


class Recipe(models.Model):
    title = models.CharField(max_length=65)
    description = models.CharField(max_length=200)
    slug = models.SlugField()
    preparation_time = models.IntegerField()
    preparation_time_unit = models.CharField(max_length=65)
    servings = models.IntegerField()
    servings_unit = models.CharField(max_length=65)
    preparation_steps = models.TextField()
    preparation_steps_is_html = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_published = models.BooleanField(default=False)
    cover = models.ImageField(upload_to="recipes/covers/%Y/%m/%d/%H/",
                              height_field=None, width_field=None, max_length=None, blank=True, default='')
    category = models.ForeignKey(
        Category, on_delete=models.SET_NULL, null=True, blank=True, default=None)
    author = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, blank=True, default=None)

    def __str__(self):
        return self.title

recipes/views.py
from django.http import Http404, HttpResponse
from django.shortcuts import get_list_or_404, get_object_or_404, render

from utils.recipes.factory import make_recipe

from .models import Recipe

# Create your views here.


def my_home(request):
    recipes = Recipe.objects.filter(
        is_published=True).order_by('-id')
    return render(request, 'recipes/pages/home.html', context={
        'recipes': recipes,
    })


def recipe(request, id):

    recipe = get_object_or_404(Recipe, id=id, is_published=True)

    return render(request, 'recipes/pages/recipe-view.html', context={
        'recipe': recipe,
        'recipe_detail': True,
    })


def category(request, category_id):

    category = get_list_or_404(Recipe.objects.filter(
        category__id=category_id, is_published=True).order_by('-id'))

    return render(request, 'recipes/pages/category.html', context={
        'recipes': category,
        'title': f' | Category - {category[0].category.name}'
    })

recipes/templates/recipes/pages/category.html
{% extends 'globais/base-recipes.html' %}
{% block title %}{{ title }}{% endblock title %}
{% block content %}
<div class="main-content main-content-list container ">
   {% for recipe in recipes %}
      {% include 'recipes/partials/recipe.html' %}
   {% endfor %}
</div>
{% endblock content %}

recipes/templates/recipes/pages/home.html
{% extends 'globais/base-recipes.html' %}
{% block title %} | home{% endblock title %}
{% block content %}
<div class="main-content main-content-list container ">
   {% for recipe in recipes  %}
      {% include 'recipes/partials/recipe.html' %}
   {% empty %}
      <div class="center m-y">
         <h1>Modules not found here!</h1>
      </div>
   {% endfor %}
</div>
{% endblock content %}

recipes/templates/recipes/pages/recipe-view.html
{% extends 'globais/base-recipes.html' %}
{% block title %} | recipe{% endblock title %}
{% block content %}
<div class="main-content main-content-detail container ">
   {% include 'recipes/partials/recipe.html' %}
</div>
{% endblock content %}

recipes/templates/recipes/partials/footer.html
<footer class="main-footer">
    <div class="developer">
        <a href="" target="_blank" rel="noreferrer noope"><p> By Isac Souza</p></a>
    </div>
    <div class="powered">
        <a href="https://www.djangoproject.com/" target="_blank" rel="noreferrer noope"><p> Powered by Django</p></a>
    </div>
</footer>

recipes/templates/recipes/partials/head.html
{% load static %}

<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial -scale=1.0">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/fontawesome.min.css"
    integrity="sha512-giQeaPns4lQTBMRpOOHsYnGw1tGVzbAIHUyHRgn7+6FmiEgGGjaG0T2LZJmAPMzRCl+Cug0ItQ2xDZpTmEc+CQ=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/brands.min.css"
    integrity="sha512-G/T7HQJXSeNV7mKMXeJKlYNJ0jrs8RsWzYG7rVACye+qrcUhEAYKYzaa+VFy6eFzM2+/JT1Q+eqBbZFSHmJQew=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/solid.min.css"
    integrity="sha512-6mc0R607di/biCutMUtU9K7NtNewiGQzrvWX4bWTeqmljZdJrwYvKJtnhgR+Ryvj+NRJ8+NnnCM/biGqMe/iRA=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@900&display=swap" rel="stylesheet">
<link rel="stylesheet" href="{% static 'recipes/css/styles.css' %}">

recipes/templates/recipes/partials/header.html
<header class="main-header-container">
    <div class="main-header container">
       <h1>
          <a class="main-logo" href ={% url 'recipes:home' %}>
             <i class="fas fa-light fa-utensils main-logo-icon"></i> 
             <span class="main-logo-text">Recipes</span>
          </a>
          
       </h1>
    </div>
</header>

recipes/templates/recipes/partials/recipe.html
<div class="recipe recipe-list-item">
   {% if recipe.cover %}
      <div class="recipe-cover">
         <a href={% url 'recipes:recipe' recipe.id %}>
            <img src={{ recipe.cover.url }} alt="temporario">
         </a>
      </div>
   {% endif %}
    <div class="recipe-title-container">
      <a href={% url 'recipes:recipe' recipe.id %}>
         <h2 class="recipe-title">{{recipe.title}}</h2>
      </a>
    </div>
    <div class="recipe-author">
      {% if recipe.author is not None %}
         <span class="recipe-author-item">
            <i class="fas fa-user"></i>
            {% if recipe.author.first_name %}
               {{ recipe.author.first_name }} {{ recipe.author.last_name }}
            {% else %}
               {{ recipe.author.username }}
            {% endif %}        
         </span>
      {% else %}
      <span class="recipe-author-item">
         <i class="fas fa-user"></i>
         Unknown      
      </span>
      {% endif %}
      <span class="recipe-author-item">
         <i class="fas fa-calendar-alt"></i>
         {{ recipe.created_at|date:"d/m/Y" }} às {{ recipe.created_at|date:"H:i" }}
      </span>
      {% if recipe.category is not None %}
         <span class="recipe-author-item">
            <a href={% url 'recipes:category' recipe.category_id %}>
               <i class="fas fa-layer-group"></i>
               <span> {{ recipe.category.name }}</span>
            </a>
         </span>
      {% endif %}
    </div>
    <div class="recipe-content">
       <p>{{ recipe.description }}</p>
    </div>
    <div class="recipe-meta-container">
       <div class="recipe-meta recipe-preparation">
          <h3 class="recipe-meta-title"><i class="fas fa-stopwatch"></i>Preparo</h3>
          <div class="recipe-meta-text">
             {{ recipe.preparation_time }} {{ recipe.preparation_time_unit }}
          </div>
       </div>
       <div class="recipe-meta recipe-servings">
          <h3 class="recipe-meta-title"><i class="fas fa-pizza-slice"></i>Porçoes</h3>
          <div class="recipe-meta-text">
            {{ recipe.servings }}
          </div>
       </div>
    </div>
    {% if not recipe_detail %}
   <footer class="recipe-footer">
       <a href={% url 'recipes:recipe' recipe.id %} class="recipe-read-more button button-dark button-full-width">
          <i class="fas fa-eye"></i>
          <span>ver</span>
       </a>
    </footer>
    {% endif %}
    {% if recipe_detail is True %}
      <div class="preparation-steps">
      {% if recipe.preparation_steps_is_html is True %}
         {{ recipe.preparation_steps|safe }}
      {% else %}
         {{ recipe.preparation_steps|linebreaksbr }}
      {% endif %}
      </div>
    {% endif %}

 </div>

recipes/templates/recipes/partials/search.html
<div class="search-container">
    <div class="container">
       <form class="search-form" action="">
          <input class="seach-input" type="search" name="search">
          <button class="search-button" type="submit"><i class="fas fa-search"></i></button>
       </form>
    </div>
 </div>